# Generated by Django 4.2 on 2023-04-25 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_cuisine_recipes_cuisine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuisine',
            name='description',
        ),
    ]
