# Generated by Django 4.2 on 2023-05-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
